server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: module-mcs-customer
          uri: lb://module-mcs-customer
          predicates:
            - Path=/customers/**
        - id: module-mcs-products
          uri: lb://module-mcs-products
          predicates:
            - Path=/products/**    
        - id: module-mcs-shopping
          uri: lb://module-mcs-shopping
          predicates:
            - Path=/invoices/**