spring:  
  h2:
    console:
      enabled: true
  datasource:
    url: 'jdbc:h2:mem:customerDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    driver-class-name: org.h2.Driver
    username: sa
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8092
  error:
    include-stacktrace: never
logging:
  pattern:
    console: '"%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:%5p} %m%n"'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: "*"     