spring:  
  application:
    name: customers
  h2:
    console:
      enabled: true
  datasource:
    url: 'jdbc:h2:mem:productDB;DB_CLOSE_DELAY'
    driver-class-name: org.h2.Driver
    username: sa
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: '8092'
  error:
    include-stacktrace: never
logging:
  pattern:
    console: '"%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:%5p} %m%n"'