spring:
  application:
    name: module-mcs-shopping
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      username: root
      password: S3CR3T
    openfeign:
      circuitbreaker:
        enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8086
management:
  endpoints:
    web:
      exposure:
        include: "*"

