# Para pasar los test agregar 127.0.0.1 -> config-server a /etc/hosts
# Para pasar el test de H2 se debe tener desplegado config-server en localhost, o de lo contrario traer la config aqui
hostname:
  customers: localhost
  products: localhost
spring:
  application:
    name: module-mcs-shopping
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      username: root
      password: S3CR3T
    openfeign:
      circuitbreaker:
        enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8086
