# Para pasar los test agregar 127.0.0.1 -> config-server a /etc/hosts 
spring:
  application:
    name: module-mcs-products
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      username: root
      password: S3CR3T
  boot:
    admin:
      client:
        url: http://localhost:8086