spring:
  application:
    name: gateway
  config:
    # import: optional:configserver:http://localhost:8888
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      # uri: http://localhost:8888
      uri: http://config-server:8888
      username: root
      password: S3CR3T