spring:
  application:
    name: eureka-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      enabled: true
      uri: http://config-server:8888
      username: root
      password: S3CR3T
      failFast: true
      retry:
        maxAttempts: 3
