version: '3.8'
services:
  config-server:
    image: yensei-app-spring-cloud/config-server:latest
    build:
      context: ../config-server
      dockerfile: Dockerfile
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "${SPRING_CLOUD_CONFIG_SERVER_GIT_URI:-https://github.com/yensei/app-spring-cloud.git}"
      SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATH: "config-data"
      SPRING_CLOUD_CONFIG_SERVER_DEFAULT_LABEL: "main"
    ports:    
      - "8888:8888"    
  eureka-server:
    image: yensei-app-spring-cloud/eureka-server:latest
    build:
      context: ../eureka-server
      dockerfile: DockerfileEureka
    ports:
      - "8099:8099"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      # SPRING_APPLICATION_NAME: eureka-service
      # SPRING_CLOUD_CONFIG_USERNAME: root
      # SPRING_CLOUD_CONFIG_PASSWORD: S3CR3T
      # SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      # EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8099/eureka
      #  SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8099/eureka"}}}}'
    links:
      - config-server
    depends_on:
      - config-server
    restart: on-failure
    healthcheck:
      test: ["CMD","wget","--spider", "-S", "http://config-server:8888"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s